import logging
import os.path

from enum import Enum

from dotenv import load_dotenv
load_dotenv()


OPENAI_API_KEY = os.environ['OPENAI_API_KEY']

# SLACK STUFF
SLACK_BOT_TOKEN = os.environ['SLACK_BOT_TOKEN']
SLACK_SIGNING_SECRET = os.environ['SLACK_SIGNING_SECRET']
SLACK_CLIENT_ID = os.environ['SLACK_CLIENT_ID']
SLACK_CLIENT_SECRET = os.environ['SLACK_CLIENT_SECRET']
SLACK_FILE_INSTALLATION_STORE_BASEDIR=os.path.expandvars(os.environ['SLACK_FILE_INSTALLATION_STORE_BASEDIR'])
SLACK_OAUTH_STATE_STORE_BASEDIR=os.path.expandvars(os.environ['SLACK_OAUTH_STATE_STORE_BASEDIR'])
logging.info("SLACK_FILE_INSTALLATION_STORE_BASEDIR: " + SLACK_FILE_INSTALLATION_STORE_BASEDIR)
logging.info("SLACK_OAUTH_STATE_STORE_BASEDIR: " + SLACK_OAUTH_STATE_STORE_BASEDIR)

# LOGGING
LOGGING_LEVEL = os.environ['LOGGING_LEVEL']
logging.getLogger().setLevel(LOGGING_LEVEL)

# STORAGE MODE
StorageMode = Enum("StorageMode", ["LOCAL", "AZURE_SEARCH"])
STORAGE_MODE = StorageMode[os.environ["STORAGE_MODE"]]
logging.info("STORAGE_MODE: " + str(STORAGE_MODE))


# CHROMADB
CHROMADB_PERSIST_DIRECTORY = os.path.expandvars(os.environ['CHROMADB_PERSIST_DIRECTORY'])
logging.info("CHROMADB_PERSIST_DIRECTORY: " + CHROMADB_PERSIST_DIRECTORY)

# AZURE COGNITIVE SEARCH
EMBEDDINGS_MODEL = os.environ["EMBEDDINGS_MODEL"]
COGNITIVE_SEARCH_STORE_ADDRESS = os.environ["COGNITIVE_SEARCH_STORE_ADDRESS"]
COGNITIVE_SEARCH_STORE_PASSWORD = os.environ["COGNITIVE_SEARCH_STORE_PASSWORD"]
COGNITIVE_SEARCH_STORE_INDEX_NAME = os.environ["COGNITIVE_SEARCH_STORE_INDEX_NAME"]

logging.info("EMBEDDINGS_MODEL: " + EMBEDDINGS_MODEL)
logging.info("COGNITIVE_SEARCH_STORE_ADDRESS: " + COGNITIVE_SEARCH_STORE_ADDRESS)
logging.info("COGNITIVE_SEARCH_STORE_PASSWORD: " + COGNITIVE_SEARCH_STORE_PASSWORD)
logging.info("COGNITIVE_SEARCH_STORE_INDEX_NAME: " + COGNITIVE_SEARCH_STORE_INDEX_NAME)